apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  labels:
    app: nginx-app
    type: nginx 
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        type: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:stable
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app