apiVersion: v1
kind: Pod
metadata:
  name: db-mysql
  labels:
    app: db-mysql
    type: database
spec:
  containers:
    - name: db-mysql-container
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: 1234@abcd
        - name: "MYSQL_DATABASE"
          value: app
        - name: "MYSQL_PASSWORD"
          value: 1234@abcd